apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-policy-updater
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-policy-updater-role
rules:
- apiGroups: ["networking.k8s.io", "cilium.io"]
  resources: ["networkpolicies", "ciliumnetworkpolicies"]
  verbs: ["get", "list", "create", "update", "patch", "apply"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-policy-updater-binding
subjects:
- kind: ServiceAccount
  name: network-policy-updater
  namespace: default
roleRef:
  kind: ClusterRole
  name: network-policy-updater-role
  apiGroup: rbac.authorization.k8s.io